[project]
mapping    = "src:.build"

[plugins.spa]
title      = "iiPython"
title_sep  = " / "
target     = "#content"
mapping    = "pages:."
external   = true

[plugins.minify]
suffixes   = [".html", ".js"]
